### ISSUE TITLE
 The performance given by yours does not correspond to the paper.

### ISSUE THREAD

**Issue by lianxi-fan** [BUPTDM/OpenHINE#13]
The performance of **HAN** and other comparison methods (such as **HERec**) reported in the paper **Heterogeneous Graph Attention Network** is inconsistent with the performance given by your homepage. 
Could you explain it？Thank you.

**Comment by Theheavens** [comment]
Our datasets contain only edges without feature information. So we ran HAN without feature and i thinkt it harms HAN's performance.

**Comment by lianxi-fan** [comment]
Thanks a lot.
