### ISSUE TITLE
What is the relationship between edge.txt and label.txt?

### ISSUE THREAD

**Issue by panda421** [BUPTDM/OpenHINE#14]
What does content of label.txt mean?
Thank You!

**Comment by Theheavens** [comment]
The label.txt is used in the downstrem task -- node classification. And it can be used as semi-supervised information in HAN. The original label information means the paper node belongs to a specific domain in acm or dblp. The edge.txt is used to construct the graph.

**Comment by panda421** [comment]
Thank you for your reply! I am confused that how the first column in label.txt corresponds to the node in edge.txt in HAN. For example, in acm data set，the first line in label.txt is "p0 2". What does p0 means and how does the p0 correspond to the node?

**Comment by Theheavens** [comment]
In edge.txt of acm, u can see "0	2036	p-a	1". That means p0 is connected with a2036 in the acm graph.

**Comment by panda421** [comment]
Sorry for the late reply.
For example, a small graph in HAN:
label.txt
p1  0
a2  1
a3  1
s4  2

edge.txt
1	3	p-a 1
3	4	a-s 1
2	1	a-p 1

config.ini
[HAN]
dim = 64
alpha = 0.005
epochs = 1
lr_decay = 0.001
patience = 100
metapath_list = pap
featype = adj

but there is something in code
`File "/OpenHINE/src/utils/sampler.py", line 296, in data_process
    al_l[int(key[1:])] = value
IndexError: index 1 is out of bounds for axis 0 with size 1`

**Comment by Theheavens** [comment]
The index of the nodes needs to start from 0.

**Comment by Theheavens** [comment]
In egde.txt, it has p1, a3, s4, a2, p1. It should be p0, a1, a2, s0.
