### ISSUE TITLE
An error when training

### ISSUE THREAD

**Issue by xing969541** [BUPTDM/OpenHINE#24]
I run:
`python train.py -m Metapath2vec -d yelp`
and get the following error:
`Traceback (most recent call last):`
`  File "train.py", line 162, in <module>`
`    main()`
`  File "train.py", line 46, in main`
`    m2v.train()`
`  File "C:\Users\Administrator\Desktop\OpenHINE-master\src\model\Metapath2vec.py", line 272, in train
    optimizer = optim.SparseAdam(self.skip_gram_model.parameters(), lr=self.initial_lr)`
`  File "C:\Program Files (x86)\Anaconda3\envs\ML1\lib\site-packages\torch\optim\sparse_adam.py", line 49, in __init__
    super(SparseAdam, self).__init__(params, defaults)`
`  File "C:\Program Files (x86)\Anaconda3\envs\ML1\lib\site-packages\torch\optim\optimizer.py", line 47, in __init__
    raise ValueError("optimizer got an empty parameter list")`
`ValueError: optimizer got an empty parameter list`
I installed pytorch version 1.7, other environments are the same as the requirements. Is this problem caused by the higher version of pytorch? How can I fix this problem by modifying the code, or I must reconfigure the environment?

**Comment by Theheavens** [comment]
Yeah, that is caused by the torch version 1.7 and someone has ever encountered it. If u want to modify the code, just change the optimizer. 
And I just tried the below code.
line 272, in train optimizer = optim.SGD(self.skip_gram_model.parameters(), lr=self.initial_lr)
But the performance of the model can't be guaranteed.

**Comment by xing969541** [comment]
Thanks for your reply. It works.
And I want to know, is label.txt necessary? I want to make link prediction for my data, and I don't think there is a distinct classification within each type of node.

**Comment by Theheavens** [comment]
U are right. I just fix the bug. In the src/config.ini set the evaluation_flag False cause it's used to evaluate the node classification.

**Comment by Theheavens** [comment]
The first problem is a bug of torch 1.7. And it can be modified like that "optimizer = optim.SparseAdam(list(self.skip_gram_model.parameters()), lr=self.initial_lr)"

**Comment by xing969541** [comment]
I've got it. Thanks for your help.
