### ISSUE TITLE
Adding new dataset

### ISSUE THREAD

**Issue by Pselen** [BUPTDM/OpenHINE#25]
Hi! 
I would like to learn the changes that need to be done in the code while adding a new dataset. 
I create a similar edge.txt file for drug-drug interaction as shown below:
5328940	43815	d-d	1
5328940	2585	d-d	1
And label.txt file as follows:
5328940	1
208908	1
But I got errors in sampler.py.  
Thanks in advance!

**Comment by Theheavens** [comment]
Which model you want to run? The node id should be set from 0 and in a row. (0,1,2... num_nodes-1)

**Comment by Pselen** [comment]
Thank you for the response. I correct it as you said: 
| edge.txt: |  |  |  | label.txt: |  |  |
|-|-|-|-|-|-|-|
| 0 | 45 | d-d | 1 | d0 | 1 |  |
| 0 | 47 | d-d | 1 | d1 | 1 |  |
| 1 | 48 | d-d | 1 | d2 | 1 |  |
| . |   |   |  | . |  |  |
| . |  |  |  | . |  |  |
| 50 | 20 | d-d | 1 | d101 | 1 |  |

However, I got errors while running HAN model in the sampler.py as "IndexError: index 51 is out of bounds for axis 0 with size 51.  I also tried to update config.ini and I added:
[drugbank]
data_type = d
relation_list = d-d
metapath_list = ddd|ddddd
Please let me know if you see the mistake!
Thanks in advance!

**Comment by Theheavens** [comment]
It seems like nodes in label.txt are not in the edge.txt. If it‘s not，show more info to solve it please

发自我的iPhone

在 2021年3月4日，19:44，Selen Parlar <notifications@github.com> 写道：

﻿

Thank you for the response. I correct it as you said:

edge.txt:                               label.txt:
0       45      d-d     1       d0      1
0       47      d-d     1       d1      1
1       48      d-d     1       d2      1
.                               .
.                               .
50      20      d-d     1       d101    1

However, I got errors while running HAN model in the sampler.py as "IndexError: index 51 is out of bounds for axis 0 with size 51. I also tried to update config.ini and I added:
[drugbank]
data_type = d
relation_list = d-d
metapath_list = ddd|ddddd
Please let me know if you see the mistake!
Thanks in advance!
